class Elves < Formula
  desc "Generate the initial project directory from the json file generated by tree."
  homepage "https://github.com/nukoneko-tarou/elves"
  url "https://github.com/nukoneko-tarou/elves/releases/download/v1.0.0/elves"
  sha256 "b4bdb41634c6bc507fe6cd814e18611e688d43c6fe80f0895c3662efedd9dae5"
  license ""

  def install
    bin.install 'elves'
  end

  test do
    system "false"
  end
end
