class Elves < Formula
  Version = 'v1.1.0'
  version Version

  if OS.mac?
    Binary = "elves_#{Version}_darwin_amd64"
    sha256 "00a81f992b5bf358848129a7c2a54019e519b63be6a99a2ab6e5d189edf2db32"
  elsif OS.linux?
    Binary = "elves_#{Version}_linux_amd64"
    sha256 "01c16d5d5f233ac4df30bdd082958eb500a972719dd61f8b1417f1fe80650b34"
  end

  desc "Generate the initial project directory from the json file generated by tree."
  homepage "https://github.com/nukoneko-tarou/elves"
  url "https://github.com/nukoneko-tarou/elves/releases/download/#{Version}/#{Binary}"

  def install
    bin.install Binary => 'elves'
  end

  test do
    system "#{bin}/elves", 'version'
  end
end
